// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8y7Nan2aTXGL2zo9k-E2-Wh2mBqnUAPk',
    appId: '1:898716599465:web:eebc24ce76a9372f5f15b8',
    messagingSenderId: '898716599465',
    projectId: 'auntification-e999d',
    authDomain: 'auntification-e999d.firebaseapp.com',
    storageBucket: 'auntification-e999d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpl7nxs-c9wpxQywxCUewMa-dTyEKlmk',
    appId: '1:898716599465:android:dd1b9ca1073d3eb85f15b8',
    messagingSenderId: '898716599465',
    projectId: 'auntification-e999d',
    storageBucket: 'auntification-e999d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDggUfxK315_26YnVc2bsEwF8Md_yA3xA4',
    appId: '1:898716599465:ios:231714476378b1855f15b8',
    messagingSenderId: '898716599465',
    projectId: 'auntification-e999d',
    storageBucket: 'auntification-e999d.firebasestorage.app',
    iosBundleId: 'com.example.auntification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDggUfxK315_26YnVc2bsEwF8Md_yA3xA4',
    appId: '1:898716599465:ios:231714476378b1855f15b8',
    messagingSenderId: '898716599465',
    projectId: 'auntification-e999d',
    storageBucket: 'auntification-e999d.firebasestorage.app',
    iosBundleId: 'com.example.auntification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8y7Nan2aTXGL2zo9k-E2-Wh2mBqnUAPk',
    appId: '1:898716599465:web:e80883b9cc03d0ac5f15b8',
    messagingSenderId: '898716599465',
    projectId: 'auntification-e999d',
    authDomain: 'auntification-e999d.firebaseapp.com',
    storageBucket: 'auntification-e999d.firebasestorage.app',
  );

}